config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :playlists do
    resources :subscriptions, only: [:create, :destroy]
    resources :items do
      resources :votes, only: [:create]
      delete "votes", :to => "votes#destroy"
    end
  end

  root "playlists#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  before_save :default_values
  belongs_to :playlist
  has_many :votes, dependent: :destroy
  scope :ordered_by_votes, -> { order(rank: :desc, created_at: :asc) }
  
  # TODO: Extract constant values to separate file
  YT_LINK_FORMAT = /\Ahttp(?:s?):\/\/(?:www\.)?youtu(?:be\.com\/watch\?v=|\.be\/)([\w\-\_]*)(&(amp;)?‌​[\w\?‌​=]*)?\z/

  validates :ytlink, presence: true, format: YT_LINK_FORMAT

  def uid
    ytlink.match(YT_LINK_FORMAT)[1]
  end

  private
  def default_values
    self.rank ||= 0
  end
end

app/models/item_observer.rb
class ItemObserver < ActiveRecord::Observer
    def before_save(resource)
        video = Yt::Video.new url: resource.ytlink
        resource.title = video.title
        resource.thumbnail_url = video.thumbnail_url
    rescue Yt::Errors::NoItems
        resource.title = ''; resource.thumbnail_url = ''
    end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
    has_many :items, dependent: :destroy
    has_many :subscriptions, dependent: :destroy
    belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :playlists
  has_many :subscriptions
  has_many :following_playlists, through: :subscriptions, source: :playlist
  has_many :votes
  has_many :upvoted_items, through: :votes, source: :item
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  validates :item, uniqueness: { scope: :user, message: "User can vote only once per item." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # For testing with Postman uncomment line below
  # protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_playlist
    before_action :set_item, except: [:create]
    before_action :authenticate_user!

    def create
        @item = @playlist.items.build()
        @item.ytlink = params[:ytlink]

        if @item.save
            render :status => 201, :json => @item
        else
            err_msg = @item.errors.empty?? 'Save failed' : @item.errors.full_messages.join('; ')
            render :status => 400, :json => { message: err_msg }
        end
    end

    def destroy
        if @item.destroy
            render json: {
                status: 200
            }
        end
    end

    private

    def set_playlist
        @playlist = Playlist.find(params[:playlist_id])
    end

    def set_item
        @item = @playlist.items.find(params[:id])
    end

    def item_params
        params[:item].permit(:ytlink)
    end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = current_user.playlists.build
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = current_user.playlists.build(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_playlist
  before_action :set_subscription, only: [:destroy]
  before_action :authenticate_user!

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = current_user.subscriptions.create(subscription_params)
    redirect_to @playlist
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_playlist
      @playlist = Playlist.find(params[:playlist_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      {:playlist_id => @playlist.id}
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:destroy]
  before_action :set_item
  before_action :set_playlist
  before_action :authenticate_user!

  # POST /votes
  # POST /votes.json
  def create
    @vote = current_user.votes.build(vote_params)

    # TODO: Do this within one ActiveRecord transaction; Move to new @item.add_vote method
    respond_to do |format|
      if @vote.save && @item.increment!(:rank)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { redirect_to @playlist, notice: 'You have already voted for this item.' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  # TODO: Do this within one ActiveRecord transaction;  Move to new @item.remove_vote method
  def destroy
    @vote.destroy
    @item.decrement!(:rank)
    respond_to do |format|
      format.html { redirect_to @playlist }
      format.json { head :no_content }
    end
  end

  private

    def set_item
      @item = Item.find(params[:item_id])
    end

    def set_playlist
      @playlist = Playlist.find(params[:playlist_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = current_user.votes.find_by_item_id(params[:item_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      {:item_id => @item.id}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/items/_form.html.slim
=  form_for([@playlist, @playlist.items.build]) do 
    input type="text" name="new_item_link" id="new_item_link"
    br
    input type="button" value="Submit" id="add_item_submit"

app/views/items/_item.html.slim
#wrapper
  #item
    p
      = item.title
    img src=item.thumbnail_url class="yt_thumbnail" data-uid=item.uid data-id=item.id
    p 
      |
        Votes: 
      = item.rank
      <br><br>
  #voting
    - if user_signed_in?
      = link_to "Add vote ", playlist_item_votes_path(@playlist, {:item_id => item.id}), method: :post, class: "btn btn-success"
      <br>
      = link_to "Remove vote", playlist_item_votes_path(@playlist, {:item_id => item.id}), method: :delete, class: "btn btn-warning"
hr align="left"

app/views/layouts/application.html.slim
doctype html
html
  head
    script src="http://www.youtube.com/player_api"
    title
      | VideoPlaylist
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    p.alert
      = alert
    - if user_signed_in?
      = link_to  "Sign Out", destroy_user_session_path, method: :delete, id: "sign_out"
    = yield

app/views/playlists/_form.html.slim
= form_for(@playlist) do |f|
  - if @playlist.errors.any?
    #error_explanation
      h2
        = pluralize(@playlist.errors.count, "error")
        |  prohibited this playlist from being saved:
      ul
        - @playlist.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .actions
    = f.submit

app/views/playlists/edit.html.slim
h1
  | Editing Playlist
= render 'form'
= link_to 'Show', @playlist
|  | 
= link_to 'Back', playlists_path

app/views/playlists/index.html.slim
p#notice
  = notice
h1
  | My Playlists
#my_playlists_list
  / Adding new playlist should be done async without page reload
  = link_to 'New Playlist', new_playlist_path, class: 'btn btn-primary'
  table 
    thead
      tr
        th
          | Name
        th[colspan="3"]
    tbody
      - current_user.playlists.each do |playlist|
        tr
          td
            = link_to playlist.name, playlist, method: :get 
          - if playlist.user == current_user
            td
              = link_to 'Edit', edit_playlist_path(playlist)
            td
              = link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }
br
h1
    | Following
#following_list
  table
    thead
      tr
        th
          | Name
        th[colspan="3"]
    tbody
      - current_user.following_playlists.each do |playlist|
        tr
          td
            = link_to playlist.name, playlist, method: :get
          - if playlist.user == current_user
            td
              = link_to 'Edit', edit_playlist_path(playlist)
            td
              = link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }

app/views/playlists/new.html.slim
h1
  | New Playlist
= render 'form'
= link_to 'Back', playlists_path

app/views/playlists/show.html.slim
#playlist_container
  p#notice
    = notice
  p#playlist_name
    strong
      = @playlist.name

    - following = current_user.following_playlists.include?(@playlist)
    - if following
      button type="button" class="btn btn-default" id="unfollow_btn" disabled="true" Unfollow
      button type="button" class="btn btn-info btn-lg" id="add_item_btn" data-toggle="modal" data-target="#addItemModal" Add Item
    - else
      = link_to 'Follow', playlist_subscriptions_path(@playlist.id), method: :post, class: "btn btn-default", id: "follow_btn"
  br
  #player
  #items_wrapper
    = render  @playlist.items.ordered_by_votes

  = link_to 'Back', playlists_path

  /  MODAL - Add Item
  .modal.fade id="addItemModal" role='dialog'
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          h4.modal-title = "Add new YouTube video"
        .modal-body
          =  form_for([@playlist, @playlist.items.build]) do 
              input type="text" name="new_item_link" class="form-control" placeholder="http://www.youtube.com/1a2b3c4d5fA" id="new_item_link"
        .modal-footer
          button.btn.btn-danger type='button' data-dismiss='modal' Close
          button.btn.btn-primary type='button' id="add_item_submit" Save

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">The following errors were found while submitting the form:</h3>
  </div>

  <div class="panel-body">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>